### ISSUE TITLE
コンポーネントのシリアライズに失敗してhrpsys.launchが上がらない

### ISSUE THREAD

**Issue by eisoku9618** [start-jsk/rtmros_common#725]
jaxon_hrpsys.launchを上げると以下のようにエラーで落ちることがあります．
（PCをbootして，最初の一回だけ起こる気がします）

@k-okada 先生がこのエラーに詳しいと伺いましたが，どうしたらよいか教えていただけますでしょうか．
ご確認よろしくお願いします．

```bash
[rtm.py]    Connect RobotHardware0.q - te.qCurrentIn
[rtm.py]    Connect sh.qOut - te.qRefIn
[rtm.py]    Connect tf.tauOut - te.tauIn
[hrpsys.py] activating components
error in serialize <hrpsys.rtm.RTcomponent instance at 0x9d9ed0c> of [<hrpsys.rtm.RTcomponent instance at 0x9d9682c>, <hrpsys.rtm.RTcomponent instance at 0x9ca0a0c>, <hrpsys.rtm.RTcomponent instance at 0x9da230c>, <hrpsys.rtm.RTcomponent instance at 0x9d9eb8c>, <hrpsys.rtm.RTcomponent instance at 0x9d9ec6c>, <hrpsys.rtm.RTcomponent instance at 0x9d9ed0c>, <hrpsys.rtm.RTcomponent instance at 0x9da042c>, <hrpsys.rtm.RTcomponent instance at 0x9d9e24c>, <hrpsys.rtm.RTcomponent instance at 0x9da06ac>, <hrpsys.rtm.RTcomponent instance at 0x9d9e92c>, <hrpsys.rtm.RTcomponent instance at 0x9da0a8c>, <hrpsys.rtm.RTcomponent instance at 0x9e70dac>, <hrpsys.rtm.RTcomponent instance at 0x9d96ccc>, <hrpsys.rtm.RTcomponent instance at 0x9d96c6c>] CORBA.COMM_FAILURE(omniORB.COMM_FAILURE_WaitingForReply, CORBA.COMPLETED_MAYBE)
Traceback (most recent call last):
  File "/home/leus/ros/hydro/src/jsk-ros-pkg/trans_system/jaxon_ros_bridge/scripts/jaxon_hrpsys.py", line 261, in <module>
    JAXONHrpsysConfigurator().init(sys.argv[1], sys.argv[2])
  File "/home/leus/ros/hydro/src/jsk-ros-pkg/trans_system/jaxon_ros_bridge/scripts/jaxon_hrpsys.py", line 32, in init
    HrpsysConfigurator.init(self, robotname, url)
  File "/home/leus/ros/hydro_parent/devel/lib/python2.7/dist-packages/hrpsys/hrpsys_config.py", line 1950, in init
    self.activateComps()
  File "/home/leus/ros/hydro_parent/devel/lib/python2.7/dist-packages/hrpsys/hrpsys_config.py", line 469, in activateComps
    rtm.serializeComponents(rtcList)
  File "/home/leus/ros/hydro_parent/devel/lib/python2.7/dist-packages/hrpsys/rtm.py", line 466, in serializeComponents
    raise e
omniORB.CORBA.COMM_FAILURE: CORBA.COMM_FAILURE(omniORB.COMM_FAILURE_WaitingForReply, CORBA.COMPLETED_MAYBE)
[hrpsys-2] process has died [pid 5137, exit code 139, cmd sudo env -i LANG=C ORBgiopMaxMsgSize=2147483648 PATH=/home/leus/ros/hydro_parent/devel/share/euslisp/jskeus/eus//Linux/bin:/home/leus/ros/hydro/devel/bin:/home/leus/ros/hydro_parent/devel/bin:/opt/ros/hydro/bin:/opt/intel/composer_xe_2015.2.164/bin/ia32:/home/leus/ros/hydro_parent/devel/share/euslisp/jskeus/eus//Linux/bin:/opt/intel/composer_xe_2015.2.164/bin/ia32:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/leus/fsharp/FSharp-2.0.0.0/bin:/home/leus/fsharp/FSharp-2.0.0.0/bin LD_LIBRARY_PATH=/home/leus/ros/hydro_parent/devel/share/euslisp/jskeus/eus//Linux/lib:/home/leus/ros/hydro/devel/lib:/home/leus/ros/hydro_parent/devel/lib:/opt/ros/hydro/lib:/opt/intel/composer_xe_2015.2.164/compiler/lib/ia32:/opt/intel/composer_xe_2015.2.164/mpirt/lib/ia32:/opt/intel/composer_xe_2015.2.164/ipp/../compiler/lib/ia32:/opt/intel/composer_xe_2015.2.164/ipp/lib/ia32:/opt/intel/composer_xe_2015.2.164/ipp/tools/ia32/perfsys:/opt/intel/composer_xe_2015.2.164/compiler/lib/ia32:/opt/intel/composer_xe_2015.2.164/mkl/lib/ia32:/opt/intel/composer_xe_2015.2.164/tbb/lib/ia32/gcc4.4:/opt/intel/composer_xe_2015.2.164/debugger/ipt/ia32/lib:/opt/ros/hydro/lib/python2.7/dist-packages /home/leus/ros/hydro_parent/devel/lib/openrtm_aist/bin/rtcd -o manager.is_master:YES   -o corba.nameservers:localhost:15005   -o corba.endpoint:10.13.3.11:  -o naming.formats:%n.rtc   -o logger.file_name:/tmp/rtc%p.log,stdout   -o logger.enable:YES -o logger.log_level:NORMAL -o logger.file_name:stdout -o exec_cxt.periodic.rate:200 -o manager.shutdown_onrtcs:NO -o manager.modules.load_path:/home/leus/ros/hydro/src/jsk-ros-pkg/trans_system/hrpsys_trans_bridge/lib,/home/leus/ros/hydro_parent/devel/share/hrpsys/lib -o manager.modules.preload:RobotHardware.so,hrpEC.so -o manager.components.precreate:RobotHardware -o exec_cxt.periodic.type:hrpExecutionContext -o example.SequencePlayer.config_file:/home/leus/ros/hydro/src/rtm-ros-robotics/rtmros_tutorials/hrpsys_ros_bridge_tutorials/models/JAXON.conf -o example.ForwardKinematics.config_file:/home/leus/ros/hydro/src/rtm-ros-robotics/rtmros_tutorials/hrpsys_ros_bridge_tutorials/models/JAXON.conf -o example.ImpedanceController.config_file:/home/leus/ros/hydro/src/rtm-ros-robotics/rtmros_tutorials/hrpsys_ros_bridge_tutorials/models/JAXON.conf -o example.AutoBalancer.config_file:/home/leus/ros/hydro/src/rtm-ros-robotics/rtmros_tutorials/hrpsys_ros_bridge_tutorials/models/JAXON.conf -o example.StateHolder.config_file:/home/leus/ros/hydro/src/rtm-ros-robotics/rtmros_tutorials/hrpsys_ros_bridge_tutorials/models/JAXON.conf -o example.TorqueFilter.config_file:/home/leus/ros/hydro/src/rtm-ros-robotics/rtmros_tutorials/hrpsys_ros_bridge_tutorials/models/JAXON.conf -o example.TorqueController.config_file:/home/leus/ros/hydro/src/rtm-ros-robotics/rtmros_tutorials/hrpsys_ros_bridge_tutorials/models/JAXON.conf -o example.ThermoEstimator.config_file:/home/leus/ros/hydro/src/rtm-ros-robotics/rtmros_tutorials/hrpsys_ros_bridge_tutorials/models/JAXON.conf -o example.ThermoLimiter.config_file:/home/leus/ros/hydro/src/rtm-ros-robotics/rtmros_tutorials/hrpsys_ros_bridge_tutorials/models/JAXON.conf -o example.VirtualForceSensor.config_file:/home/leus/ros/hydro/src/rtm-ros-robotics/rtmros_tutorials/hrpsys_ros_bridge_tutorials/models/JAXON.conf -o example.AbsoluteForceSensor.config_file:/home/leus/ros/hydro/src/rtm-ros-robotics/rtmros_tutorials/hrpsys_ros_bridge_tutorials/models/JAXON.conf -o example.RemoveForceSensorLinkOffset.config_file:/home/leus/ros/hydro/src/rtm-ros-robotics/rtmros_tutorials/hrpsys_ros_bridge_tutorials/models/JAXON.conf -o example.KalmanFilter.config_file:/home/leus/ros/hydro/src/rtm-ros-robotics/rtmros_tutorials/hrpsys_ros_bridge_tutorials/models/JAXON.conf -o example.Stabilizer.config_file:/home/leus/ros/hydro/src/rtm-ros-robotics/rtmros_tutorials/hrpsys_ros_bridge_tutorials/models/JAXON.conf -o example.CollisionDetector.config_file:/home/leus/ros/hydro/src/rtm-ros-robotics/rtmros_tutorials/hrpsys_ros_bridge_tutorials/models/JAXON.conf -o example.SoftErrorLimiter.config_file:/home/leus/ros/hydro/src/rtm-ros-robotics/rtmros_tutorials/hrpsys_ros_bridge_tutorials/models/JAXON.conf -o example.HGcontroller.config_file:/home/leus/ros/hydro/src/rtm-ros-robotics/rtmros_tutorials/hrpsys_ros_bridge_tutorials/models/JAXON.conf -o example.PDcontroller.config_file:/home/leus/ros/hydro/src/rtm-ros-robotics/rtmros_tutorials/hrpsys_ros_bridge_tutorials/models/JAXON.conf -o example.RobotHardware.config_file:/home/leus/ros/hydro/src/rtm-ros-robotics/rtmros_tutorials/hrpsys_ros_bridge_tutorials/models/JAXON.RobotHardware.conf __name:=hrpsys __log:=/home/leus/.ros/log/1047fd92-fa8c-11e4-97d9-8950e3dbd60e/hrpsys-2.log].
log file: /home/leus/.ros/log/1047fd92-fa8c-11e4-97d9-8950e3dbd60e/hrpsys-2*.log
[hrpsys_py-3] process has died [pid 5151, exit code 1, cmd /home/leus/ros/hydro/src/jsk-ros-pkg/trans_system/jaxon_ros_bridge/scripts/jaxon_hrpsys.py RobotHardware0 /home/leus/ros/hydro/src/rtm-ros-robotics/rtmros_hrp2/jsk_models/JAXON/JAXONmain.wrl -ORBInitRef NameService=corbaloc:iiop:localhost:15005/NameService __name:=hrpsys_py __log:=/home/leus/.ros/log/1047fd92-fa8c-11e4-97d9-8950e3dbd60e/hrpsys_py-3.log].
log file: /home/leus/.ros/log/1047fd92-fa8c-11e4-97d9-8950e3dbd60e/hrpsys_py-3*.log
```

https://github.com/fkanehiro/hrpsys-base/blob/master/python/rtm.py#L465

```python
print("error in serialize %s of %s %s" % (rtc,  rtcs, str(e)))
```

ではなくて

```python
print("error in serialize %s of %s %s" % (rtc.name(),  rtcs, str(e)))
```

の方がわかりやすい？

**Comment by k-okada** [comment]
エラーはよく見ていますが，残念ながら解決法には詳しくないです．
https://github.com/jsk-ros-pkg/trans_system/blob/master/jaxon_ros_bridge/launch/jaxon_hrpsys.launch

次，リブートしたら，
```
ORBgiopMaxMsgSize=2147483648 roslaunch jaxon_hrpsys.launch  % rtmlaunch?
```
してみてください．

https://github.com/fkanehiro/hrpsys-base/pull/634
でエラーは直しました．

HRP2では起きる？起きない？
@fkanehiro さんに，そっちでも起こっているか聞いてみるのは有効でしょうか．
