### ISSUE TITLE
cannot call hcf method because of CORBA.OBJECT_NOT_EXIST

### ISSUE THREAD

**Issue by garaemon** [start-jsk/rtmros_common#832]
Too early to instantiate hcf?

https://s3.amazonaws.com/archive.travis-ci.org/jobs/80775258/log.txt

```
... logging to /home/travis/.ros/log/rostest-testing-worker-linux-968a87ce-2-20307-linux-2-80775258-13184.log
[ROSUNIT] Outputting test results to /home/travis/.ros/test_results/hrpsys_tools/rostest-test_test-pa10.xml
omniORB: Failed to bind to address :: port 2809. Address in use?
omniORB: Error: Unable to create an endpoint of this description: giop:tcp::2809
Failed to initialise the ORB / POA: INITIALIZE_TransportError
Is omniNames already running?
ready
loading file:///opt/ros/hydro/share/OpenHRP-3.1/sample/project/../model/PA10/pa10.main.wrl
Humanoid node
Joint node BASE
  Segment node BASE_LINK
  Joint node J1
    Segment node J1_LINK
    Joint node J2
      Segment node J2_LINK
      Joint node J3
        Segment node J3_LINK
        Joint node J4
          Segment node J4_LINK
          Joint node J5
            Segment node J5_LINK
            Joint node J6
              Segment node J6_LINK
              Joint node J7
                Segment node J7_LINK
                Joint node HAND_L
                  Segment node HAND_L_LINK
                Joint node HAND_R
                  Segment node HAND_R_LINK
The model was successfully loaded ! 
Loading body customizer "/opt/ros/hydro/share/OpenHRP-3.1/customizer/libSampleCustomizer.so" for springJoint
configuration ORB with localhost:2809
[hrpsys.py] waiting ModelLoader
[hrpsys.py] start hrpsys
[hrpsys.py] finding RTCManager and RobotHardware
[hrpsys.py] wait for RTCmanager : None
[hrpsys.py] wait for PA10Controller(Robot)0 : <hrpsys.rtm.RTcomponent instance at 0x3ac59e0> ( timeout 0 < 10)
[hrpsys.py] findComps -> RobotHardware : <hrpsys.rtm.RTcomponent instance at 0x3ac59e0> isActive? = True 
[hrpsys.py] simulation_mode : True
[hrpsys.py]   bodyinfo URL = file:///opt/ros/hydro/share/openhrp3/share/OpenHRP-3.1/sample/model/PA10/pa10.main.wrl
loading file:///opt/ros/hydro/share/openhrp3/share/OpenHRP-3.1/sample/model/PA10/pa10.main.wrl
Humanoid node
Joint node BASE
  Segment node BASE_LINK
  Joint node J1
    Segment node J1_LINK
    Joint node J2
      Segment node J2_LINK
      Joint node J3
        Segment node J3_LINK
        Joint node J4
          Segment node J4_LINK
          Joint node J5
            Segment node J5_LINK
            Joint node J6
              Segment node J6_LINK
              Joint node J7
                Segment node J7_LINK
                Joint node HAND_L
                  Segment node HAND_L_LINK
                Joint node HAND_R
                  Segment node HAND_R_LINK
The model was successfully loaded ! 
[hrpsys.py] creating components
[hrpsys.py]   eval : [self.seq, self.seq_svc, self.seq_version] = self.createComp("SequencePlayer","seq")
loading file:///opt/ros/hydro/share/OpenHRP-3.1/sample/model/PA10/pa10.main.wrl
Humanoid node
Joint node BASE
  Segment node BASE_LINK
  Joint node J1
    Segment node J1_LINK
    Joint node J2
      Segment node J2_LINK
      Joint node J3
        Segment node J3_LINK
        Joint node J4
          Segment node J4_LINK
          Joint node J5
            Segment node J5_LINK
            Joint node J6
              Segment node J6_LINK
              Joint node J7
                Segment node J7_LINK
                Joint node HAND_L
                  Segment node HAND_L_LINK
                Joint node HAND_R
                  Segment node HAND_R_LINK
The model was successfully loaded ! 
[hrpsys.py] create Comp -> SequencePlayer : <hrpsys.rtm.RTcomponent instance at 0x3aa1128> (315.7.0)
[hrpsys.py] create CompSvc -> SequencePlayer Service : <OpenHRP._objref_SequencePlayerService instance at 0x3b6b290>
[hrpsys.py]   eval : [self.sh, self.sh_svc, self.sh_version] = self.createComp("StateHolder","sh")
cache found for file:///opt/ros/hydro/share/OpenHRP-3.1/sample/model/PA10/pa10.main.wrl
[hrpsys.py] create Comp -> StateHolder : <hrpsys.rtm.RTcomponent instance at 0x390da70> (315.7.0)
[hrpsys.py] create CompSvc -> StateHolder Service : <OpenHRP._objref_StateHolderService instance at 0x3b6cb48>
[hrpsys.py]   eval : [self.fk, self.fk_svc, self.fk_version] = self.createComp("ForwardKinematics","fk")
cache found for file:///opt/ros/hydro/share/OpenHRP-3.1/sample/model/PA10/pa10.main.wrl
cache found for file:///opt/ros/hydro/share/OpenHRP-3.1/sample/model/PA10/pa10.main.wrl
[hrpsys.py] create Comp -> ForwardKinematics : <hrpsys.rtm.RTcomponent instance at 0x3b5ec20> (315.7.0)
[hrpsys.py] create CompSvc -> ForwardKinematics Service : <OpenHRP._objref_ForwardKinematicsService instance at 0x3b6cd40>
[hrpsys.py]   eval : [self.co, self.co_svc, self.co_version] = self.createComp("CollisionDetector","co")
;;
;; Could not open /dev/console for writing.
;;
open: Permission denied
cache found for file:///opt/ros/hydro/share/OpenHRP-3.1/sample/model/PA10/pa10.main.wrl
[hrpsys.py] create Comp -> CollisionDetector : <hrpsys.rtm.RTcomponent instance at 0x3b5e368> (315.7.0)
[hrpsys.py] create CompSvc -> CollisionDetector Service : <OpenHRP._objref_CollisionDetectorService instance at 0x3b6ccb0>
[hrpsys.py]   eval : [self.el, self.el_svc, self.el_version] = self.createComp("SoftErrorLimiter","el")
;;
;; Could not open /dev/console for writing.
;;
open: Permission denied
cache found for file:///opt/ros/hydro/share/OpenHRP-3.1/sample/model/PA10/pa10.main.wrl
[el] Do not load joint limit table
[hrpsys.py] create Comp -> SoftErrorLimiter : <hrpsys.rtm.RTcomponent instance at 0x3b6f3f8> (315.7.0)
[hrpsys.py] create CompSvc -> SoftErrorLimiter Service : <OpenHRP._objref_SoftErrorLimiterService instance at 0x3b6cb90>
[hrpsys.py]   eval : [self.log, self.log_svc, self.log_version] = self.createComp("DataLogger","log")
[hrpsys.py] create Comp -> DataLogger : <hrpsys.rtm.RTcomponent instance at 0x3b6fc20> (315.7.0)
[hrpsys.py] create CompSvc -> DataLogger Service : <OpenHRP._objref_DataLoggerService instance at 0x3b68200>
[hrpsys.py] connecting components
[rtm.py]    Connect sh.qOut - co.qRef
[rtm.py]    Connect co.q - el.qRef
[rtm.py]    Connect el.q - HGcontroller0.qIn
[rtm.py]    Connect HGcontroller0.qOut - PA10Controller(Robot)0.qRef
[rtm.py]    Connect PA10Controller(Robot)0.servoState - el.servoStateIn
[rtm.py]    Connect PA10Controller(Robot)0.q - sh.currentQIn
[rtm.py]    Connect PA10Controller(Robot)0.q - fk.q
[rtm.py]    Connect sh.qOut - fk.qRef
[rtm.py]    Connect seq.qRef - sh.qIn
[rtm.py]    Connect seq.tqRef - sh.tqIn
[rtm.py]    Connect seq.basePos - sh.basePosIn
[rtm.py]    Connect seq.baseRpy - sh.baseRpyIn
[rtm.py]    Connect seq.zmpRef - sh.zmpIn
[rtm.py]    Connect seq.optionalData - sh.optionalDataIn
[rtm.py]    Connect sh.basePosOut - seq.basePosInit
[rtm.py]    Connect sh.basePosOut - fk.basePosRef
[rtm.py]    Connect sh.baseRpyOut - seq.baseRpyInit
[rtm.py]    Connect sh.baseRpyOut - fk.baseRpyRef
[rtm.py]    Connect sh.qOut - seq.qInit
[rtm.py]    Connect sh.zmpOut - seq.zmpRefInit
[rtm.py]    Connect PA10Controller(Robot)0.q - co.qCurrent
[rtm.py]    Connect PA10Controller(Robot)0.servoState - co.servoStateIn
[rtm.py]    Connect PA10Controller(Robot)0.q - el.qCurrent
[hrpsys.py] activating components
pure virtual method called
terminate called without an active exception
Traceback (most recent call last):
  File "/home/travis/ros/ws_rtmros_common/install/share/hrpsys_tools/scripts/hrpsys_tools_config.py", line 49, in <module>
    hcf.init(sys.argv[1], sys.argv[2])
  File "/opt/ros/hydro/lib/python2.7/dist-packages/hrpsys/hrpsys_config.py", line 2045, in init
    self.activateComps()
  File "/opt/ros/hydro/lib/python2.7/dist-packages/hrpsys/hrpsys_config.py", line 491, in activateComps
    rtm.serializeComponents(rtcList)
  File "/opt/ros/hydro/lib/python2.7/dist-packages/hrpsys/rtm.py", line 465, in serializeComponents
    print("[rtm.py] \033[31m   error in serialize %s of %s %s\033[0m" % (rtc.name(),  [[r, r.name()] for r in rtcs], str(e)))
  File "/opt/ros/hydro/lib/python2.7/dist-packages/hrpsys/rtm.py", line 169, in name
    cprof = self.ref.get_component_profile()
  File "/opt/ros/hydro/lib/python2.7/dist-packages/OpenRTM_aist/RTM_IDL/RTC_idl.py", line 1344, in get_component_profile
    return _omnipy.invoke(self, "get_component_profile", _0_RTC.RTObject._d_get_component_profile, args)
omniORB.CORBA.TRANSIENT: CORBA.TRANSIENT(omniORB.TRANSIENT_ConnectFailed, CORBA.COMPLETED_NO)
cache found for file:///opt/ros/hydro/share/OpenHRP-3.1/sample/project/../model/PA10/pa10.main.wrl
Loading body customizer "/opt/ros/hydro/share/OpenHRP-3.1/customizer/libSampleCustomizer.so" for springJoint
[hrpsys.py] #
[hrpsys.py] # use `hcf` as robot interface, for example hcf.getJointAngles()
[hrpsys.py] #
>> import rostest, unittest
>> import time
>> time.sleep(5)
>> hcf.setJointAngles([10,10,10,10,10,10,10,10,10], 1)
Traceback (most recent call last):
  File "/home/travis/ros/ws_rtmros_common/install/share/hrpsys_tools/scripts/hrpsys_tools_config.py", line 44, in <module>
    exec(args.c[0])
  File "<string>", line 1, in <module>
  File "/opt/ros/hydro/lib/python2.7/dist-packages/hrpsys/hrpsys_config.py", line 978, in setJointAngles
    return self.seq_svc.setJointAngles(ret, tm)
  File "/opt/ros/hydro/lib/python2.7/dist-packages/hrpsys/SequencePlayerService_idl.py", line 137, in setJointAngles
    return _omnipy.invoke(self, "setJointAngles", _0_OpenHRP.SequencePlayerService._d_setJointAngles, args)
omniORB.CORBA.OBJECT_NOT_EXIST: CORBA.OBJECT_NOT_EXIST(omniORB.OBJECT_NOT_EXIST_NoMatch, CORBA.COMPLETED_NO)
terminate called after throwing an instance of 'CORBA::OBJECT_NOT_EXIST'
testhrpsys_tool_config_interactive ... FAILURE!
FAILURE: test [hrpsys_tool_config_interactive] did not generate test results
  File "/usr/lib/python2.7/unittest/case.py", line 327, in run
    testMethod()
  File "/opt/ros/hydro/lib/python2.7/dist-packages/rostest/runner.py", line 162, in fn
    self.assert_(os.path.isfile(test_file), "test [%s] did not generate test results"%test_name)
  File "/usr/lib/python2.7/unittest/case.py", line 420, in assertTrue
    raise self.failureException(msg)
--------------------------------------------------------------------------------

[ROSTEST]-----------------------------------------------------------------------

[testhrpsys_tool_config_interactive][failed]

SUMMARY
�[1;31m * RESULT: FAIL�[0m
 * TESTS: 0
 * ERRORS: 0
�[1;31m * FAILURES: 1�[0m
```

**Comment by garaemon** [comment]
maybe `pure virtual method called
terminate called without an active exception` kills hrpsys process
